(ns gunax.sokoban.levels)

(def levels  [{:level [[:open :open :wall :wall :wall :wall :wall :open]
                        [:wall :wall :wall :open :open :open :wall :open]
                        [:wall :open :open :open :wall :open :wall :wall]
                        [:wall :open :wall :open :open :target :open :wall]
                        [:wall :open :open :open :open :wall :open :wall]
                        [:wall :wall :open :wall :open :open :open :wall]
                        [:open :wall :open :open :open :wall :wall :wall]
                        [:open :wall :wall :wall :wall :wall :open :open]]
                :positions {:player [6 3]
                            :blocks #{[2 2]}}}

              {:level [[:open :wall :wall :wall :wall :wall :wall] 
                       [:wall :wall :open :open :target :open :wall] 
                       [:wall :open :target :open :wall :open :wall] 
                       [:wall :open :target :open :open :open :wall] 
                       [:wall :open :open :wall :open :wall :wall] 
                       [:wall :wall :open :open :open :wall :open] 
                       [:open :wall :wall :wall :wall :wall :open]], 
               :positions {:player [5 4], :blocks #{[2 2] [3 3] [4 4]}}}

              {:level 
               [[:wall :wall :wall :wall :wall :wall :wall] 
                [:wall :open :open :target :open :open :wall] 
                [:wall :open :wall :target :wall :open :wall] 
                [:wall :open :open :open :open :open :wall] 
                [:wall :target :open :open :open :wall :wall] 
                [:wall :open :open :wall :wall :wall :open] 
                [:wall :wall :wall :wall :open :open :open]], 
               :positions {:player [5 4], :blocks #{[2 2] [3 3] [4 4]}}}

{:level [[:open :open :open :wall :wall :wall :wall] [:wall :wall :wall :wall :open :open :wall] [:wall :open :open :target :open :open :wall] [:wall :open :open :open :open :open :wall] [:wall :wall :open :target :wall :wall :wall] [:open :wall :open :open :wall :open :open] [:open :wall :open :target :wall :open :open] [:open :wall :wall :wall :wall :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}

{:level [[:wall :wall :wall :open :wall :wall :wall] [:wall :target :wall :wall :wall :target :wall] [:wall :open :wall :open :open :target :wall] [:wall :open :open :open :open :open :wall] [:wall :open :open :open :open :open :wall] [:wall :open :open :wall :open :open :wall] [:wall :open :open :wall :wall :wall :wall] [:wall :wall :wall :wall :open :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :open :wall :wall :wall :wall :open] [:open :open :open :wall :open :open :wall :wall] [:wall :wall :wall :wall :open :open :open :wall] [:wall :target :open :wall :open :open :open :wall] [:wall :open :open :open :open :open :wall :wall] [:wall :target :open :open :open :wall :wall :open] [:wall :wall :target :open :open :wall :open :open] [:open :wall :wall :wall :wall :wall :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :open :open :open] [:wall :open :target :target :wall :wall :wall :wall] [:wall :open :open :open :open :open :open :wall] [:wall :open :open :wall :open :wall :open :wall] [:wall :open :open :open :target :open :open :wall] [:wall :wall :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :wall :wall :wall :wall :wall] [:wall :wall :wall :open :open :target :wall] [:wall :open :open :open :wall :open :wall] [:wall :open :target :open :open :open :wall] [:wall :open :target :wall :open :open :wall] [:wall :open :open :open :open :wall :wall] [:wall :open :open :open :wall :wall :open] [:wall :wall :wall :wall :wall :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :wall :open] [:wall :target :open :open :open :target :wall :open] [:wall :open :open :open :wall :open :wall :wall] [:wall :open :wall :open :open :target :open :wall] [:wall :open :open :open :open :wall :open :wall] [:wall :wall :wall :wall :open :open :open :wall] [:open :open :open :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :open :open] [:wall :target :open :target :wall :wall :wall] [:wall :target :wall :open :open :open :wall] [:wall :open :open :open :open :open :wall] [:wall :open :open :wall :open :open :wall] [:wall :wall :open :open :open :wall :wall] [:open :wall :wall :wall :wall :wall :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :open :open] [:wall :target :open :open :wall :wall :wall] [:wall :open :wall :open :open :open :wall] [:wall :open :target :open :wall :open :wall] [:wall :open :open :target :open :open :wall] [:wall :wall :open :open :wall :wall :wall] [:open :wall :open :open :wall :open :open] [:open :wall :wall :wall :wall :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :wall :wall] [:wall :target :open :open :open :target :open :wall] [:wall :open :wall :open :wall :open :open :wall] [:wall :open :open :open :open :open :target :wall] [:wall :wall :wall :wall :wall :open :open :wall] [:open :open :open :open :wall :open :open :wall] [:open :open :open :open :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :open :open :open :open] [:wall :open :open :wall :open :open :open :open] [:wall :open :open :wall :wall :wall :wall :wall] [:wall :open :target :target :open :open :open :wall] [:wall :wall :open :open :open :open :open :wall] [:open :wall :open :wall :open :wall :wall :wall] [:open :wall :target :open :open :wall :open :open] [:open :wall :wall :wall :wall :wall :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :wall :wall :wall :wall :wall :open :open] [:open :wall :open :open :open :wall :wall :wall] [:wall :wall :open :target :open :open :open :wall] [:wall :target :open :open :target :open :open :wall] [:wall :wall :open :wall :open :wall :wall :wall] [:open :wall :open :open :open :wall :open :open] [:open :wall :wall :wall :wall :wall :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :wall :wall :wall :wall :wall :open] [:wall :wall :open :open :open :wall :open] [:wall :open :open :wall :open :wall :open] [:wall :open :target :open :open :wall :wall] [:wall :open :target :open :open :open :wall] [:wall :wall :open :wall :open :open :wall] [:open :wall :target :open :open :wall :wall] [:open :wall :wall :wall :wall :wall :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :wall :wall :wall :wall :open :open :open] [:wall :wall :open :open :wall :wall :wall :wall] [:wall :target :target :open :open :open :target :wall] [:wall :open :wall :open :open :open :open :wall] [:wall :open :open :open :wall :open :open :wall] [:wall :wall :wall :wall :wall :open :open :wall] [:open :open :open :open :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :wall :wall :wall :wall :wall :wall :open] [:open :wall :open :open :target :open :wall :wall] [:open :wall :open :open :open :open :target :wall] [:open :wall :wall :wall :target :wall :open :wall] [:wall :wall :open :open :open :open :open :wall] [:wall :open :open :open :open :open :wall :wall] [:wall :open :open :open :wall :wall :wall :open] [:wall :wall :wall :wall :wall :open :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :wall :wall :wall :wall :open :open :open] [:open :wall :open :open :wall :open :open :open] [:open :wall :open :open :wall :open :open :open] [:wall :wall :target :open :wall :wall :wall :wall] [:wall :open :open :open :target :open :target :wall] [:wall :open :open :open :open :wall :wall :wall] [:wall :wall :wall :open :open :wall :open :open] [:open :open :wall :wall :wall :wall :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :open :open] [:wall :target :open :open :wall :open :open] [:wall :open :wall :open :wall :wall :wall] [:wall :open :target :open :open :open :wall] [:wall :open :open :open :target :open :wall] [:wall :open :open :open :wall :wall :wall] [:wall :wall :wall :wall :wall :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :wall :wall :wall :wall :wall] [:open :open :wall :open :open :open :wall] [:open :open :wall :open :wall :target :wall] [:wall :wall :wall :open :open :target :wall] [:wall :open :open :open :open :open :wall] [:wall :open :open :target :open :open :wall] [:wall :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :open :open] [:wall :open :open :open :open :wall :open :open] [:wall :open :open :wall :open :wall :wall :wall] [:wall :open :target :open :open :open :open :wall] [:wall :open :open :open :wall :wall :open :wall] [:wall :wall :target :open :open :target :open :wall] [:open :wall :wall :open :open :open :wall :wall] [:open :open :wall :wall :wall :wall :wall :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :open] [:wall :open :open :open :open :wall :wall] [:wall :open :open :wall :open :open :wall] [:wall :target :open :open :open :open :wall] [:wall :open :open :open :wall :target :wall] [:wall :wall :wall :open :open :target :wall] [:open :open :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :wall :wall :wall :wall :open :open] [:wall :wall :wall :target :open :wall :open :open] [:wall :open :target :open :open :wall :wall :wall] [:wall :open :open :open :open :open :open :wall] [:wall :wall :open :target :open :open :open :wall] [:open :wall :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :wall :wall :wall :wall :wall :wall :open] [:wall :wall :open :target :open :open :wall :open] [:wall :open :open :open :target :open :wall :open] [:wall :open :open :wall :open :open :wall :wall] [:wall :open :open :wall :open :open :target :wall] [:wall :wall :wall :wall :open :wall :open :wall] [:open :open :open :wall :open :open :open :wall] [:open :open :open :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :open :open :wall :wall :wall :wall] [:open :open :open :open :wall :open :open :wall] [:open :open :wall :wall :wall :open :target :wall] [:open :open :wall :open :open :target :open :wall] [:wall :wall :wall :open :open :wall :target :wall] [:wall :open :open :open :open :open :open :wall] [:wall :open :open :open :wall :open :open :wall] [:wall :wall :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :open :open :open] [:wall :open :open :target :wall :wall :wall :open] [:wall :open :open :target :target :open :wall :open] [:wall :open :open :wall :wall :open :wall :wall] [:wall :wall :open :open :wall :open :open :wall] [:open :wall :open :open :open :open :open :wall] [:open :wall :open :open :wall :wall :wall :wall] [:open :wall :wall :wall :wall :open :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :wall :wall :wall :wall :open :open] [:open :open :wall :open :open :wall :open :open] [:open :open :wall :open :open :wall :wall :wall] [:wall :wall :wall :open :target :target :open :wall] [:wall :open :open :open :wall :open :open :wall] [:wall :open :open :target :open :open :open :wall] [:wall :wall :wall :wall :open :open :open :wall] [:open :open :open :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :open :open :open] [:wall :open :open :open :wall :wall :wall :open] [:wall :open :wall :open :target :open :wall :wall] [:wall :open :open :target :open :open :open :wall] [:wall :wall :wall :open :open :open :open :wall] [:open :open :wall :open :open :open :target :wall] [:open :open :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :wall :wall :wall :wall :wall :wall] [:wall :wall :wall :open :target :open :open :wall] [:wall :open :open :open :wall :target :open :wall] [:wall :open :open :open :wall :open :wall :wall] [:wall :open :open :target :open :open :wall :open] [:wall :wall :open :open :wall :open :wall :open] [:open :wall :wall :open :open :open :wall :open] [:open :open :wall :wall :wall :wall :wall :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :wall :wall :wall :wall :open :open :open] [:wall :wall :open :open :wall :wall :wall :open] [:wall :open :open :open :open :open :wall :wall] [:wall :open :open :wall :open :open :open :wall] [:wall :open :open :target :open :target :target :wall] [:wall :wall :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :wall :wall :wall :wall :wall :wall :wall] [:wall :wall :open :open :open :open :open :wall] [:wall :target :open :wall :open :open :open :wall] [:wall :open :open :open :open :target :wall :wall] [:wall :open :target :wall :open :open :wall :open] [:wall :open :open :wall :wall :wall :wall :open] [:wall :wall :wall :wall :open :open :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :wall :wall] [:wall :open :open :open :open :open :open :wall] [:wall :open :wall :open :wall :wall :target :wall] [:wall :open :wall :open :open :open :open :wall] [:wall :target :open :open :target :open :open :wall] [:wall :wall :wall :wall :wall :open :open :wall] [:open :open :open :open :wall :open :open :wall] [:open :open :open :open :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :wall :wall :wall :wall :wall :wall :open] [:open :wall :open :open :open :open :wall :wall] [:open :wall :wall :open :open :open :open :wall] [:wall :wall :wall :open :target :open :open :wall] [:wall :open :open :open :wall :open :wall :wall] [:wall :open :target :open :open :target :wall :open] [:wall :wall :wall :wall :open :open :wall :open] [:open :open :open :wall :wall :wall :wall :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :open :open] [:wall :open :open :open :wall :wall :wall] [:wall :open :open :open :open :open :wall] [:wall :wall :open :open :open :target :wall] [:open :wall :open :open :target :open :wall] [:open :wall :wall :open :wall :open :wall] [:open :open :wall :open :open :target :wall] [:open :open :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :open :open :open] [:wall :open :open :open :wall :wall :wall :wall] [:wall :open :open :open :open :open :open :wall] [:wall :open :target :wall :target :open :open :wall] [:wall :open :open :wall :wall :open :wall :wall] [:wall :open :open :wall :wall :open :wall :open] [:wall :open :open :open :open :target :wall :open] [:wall :wall :wall :wall :wall :wall :wall :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :open :open] [:wall :open :target :open :open :wall :open :open] [:wall :open :target :wall :open :wall :wall :wall] [:wall :open :open :open :open :open :open :wall] [:wall :open :open :target :open :open :open :wall] [:wall :wall :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :wall :wall] [:wall :open :open :target :wall :open :open :wall] [:wall :open :target :open :open :target :open :wall] [:wall :open :open :wall :open :open :open :wall] [:wall :open :open :open :open :open :wall :wall] [:wall :wall :wall :open :open :wall :wall :open] [:open :open :wall :open :open :wall :open :open] [:open :open :wall :wall :wall :wall :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :wall :wall :wall :wall :wall :wall :wall] [:wall :wall :open :open :open :target :open :wall] [:wall :open :open :open :open :open :open :wall] [:wall :target :open :target :wall :wall :wall :wall] [:wall :open :open :wall :wall :open :open :open] [:wall :open :open :wall :open :open :open :open] [:wall :open :open :wall :open :open :open :open] [:wall :wall :wall :wall :open :open :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :open] [:wall :open :target :open :open :wall :open] [:wall :open :open :wall :open :wall :open] [:wall :open :open :open :open :wall :wall] [:wall :wall :open :wall :open :open :wall] [:wall :open :open :open :wall :open :wall] [:wall :target :open :target :open :open :wall] [:wall :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :open :wall :wall :wall :wall :wall] [:wall :wall :wall :wall :open :target :open :wall] [:wall :open :target :open :open :target :open :wall] [:wall :open :open :open :wall :open :open :wall] [:wall :open :wall :open :open :open :open :wall] [:wall :open :open :open :wall :wall :wall :wall] [:wall :wall :wall :wall :wall :open :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :wall :wall :wall :wall :open :open] [:wall :wall :wall :open :open :wall :wall :wall] [:wall :open :target :target :open :open :target :wall] [:wall :open :open :open :open :open :open :wall] [:wall :wall :wall :wall :open :open :open :wall] [:open :open :open :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :open :open :wall :wall :wall :wall] [:open :open :open :open :wall :open :open :wall] [:wall :wall :wall :wall :wall :open :target :wall] [:wall :open :open :open :open :open :open :wall] [:wall :open :open :open :target :open :open :wall] [:wall :wall :wall :open :target :open :open :wall] [:open :open :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :wall :wall] [:wall :open :open :open :wall :open :open :wall] [:wall :open :wall :target :open :open :open :wall] [:wall :open :open :open :open :open :open :wall] [:wall :wall :wall :wall :wall :target :open :wall] [:open :open :wall :open :open :open :open :wall] [:open :open :wall :open :open :open :target :wall] [:open :open :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :open :wall :wall :wall :wall :open] [:open :open :wall :wall :open :open :wall :wall] [:open :wall :wall :open :open :target :target :wall] [:wall :wall :open :open :wall :open :wall :wall] [:wall :open :open :open :open :target :open :wall] [:wall :open :open :wall :open :open :open :wall] [:wall :open :open :open :open :wall :wall :wall] [:wall :wall :wall :wall :wall :wall :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :open :open] [:wall :open :open :open :open :wall :open :open] [:wall :open :open :open :wall :wall :wall :wall] [:wall :open :open :open :target :open :open :wall] [:wall :wall :open :wall :target :wall :open :wall] [:wall :target :open :open :open :wall :open :wall] [:wall :open :open :open :open :open :open :wall] [:wall :wall :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :open :wall :wall :wall :wall :open] [:open :open :open :wall :open :open :wall :open] [:wall :wall :wall :wall :open :open :wall :wall] [:wall :open :open :open :target :open :open :wall] [:wall :open :wall :wall :open :open :open :wall] [:wall :open :open :open :wall :wall :open :wall] [:wall :open :open :open :target :open :target :wall] [:wall :wall :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :open :wall :wall :wall :wall :wall] [:open :open :open :wall :open :open :open :wall] [:open :wall :wall :wall :open :open :open :wall] [:open :wall :open :open :open :open :wall :wall] [:wall :wall :open :open :open :open :wall :open] [:wall :target :open :open :wall :open :wall :open] [:wall :target :target :open :open :open :wall :open] [:wall :wall :wall :wall :wall :wall :wall :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:open :open :open :wall :wall :wall :wall :wall] [:wall :wall :wall :wall :target :open :open :wall] [:wall :open :open :target :open :open :open :wall] [:wall :open :wall :open :open :wall :wall :wall] [:wall :open :open :open :open :open :target :wall] [:wall :wall :wall :wall :open :open :open :wall] [:open :open :open :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :wall :wall] [:wall :open :open :target :wall :open :open :wall] [:wall :open :wall :open :open :open :open :wall] [:wall :open :open :target :wall :open :open :wall] [:wall :wall :open :target :open :open :open :wall] [:open :wall :open :open :wall :wall :wall :wall] [:open :wall :wall :wall :wall :open :open :open]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :wall] [:wall :open :open :open :open :open :wall] [:wall :target :wall :wall :open :target :wall] [:wall :target :open :open :open :open :wall] [:wall :open :open :wall :open :open :wall] [:wall :open :open :wall :open :open :wall] [:wall :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :open :open :open :open] [:wall :target :open :wall :open :open :open :open] [:wall :open :open :wall :open :open :open :open] [:wall :open :open :wall :wall :wall :wall :wall] [:wall :open :target :open :open :open :open :wall] [:wall :open :target :open :open :wall :open :wall] [:wall :wall :wall :open :open :open :open :wall] [:open :open :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :wall :wall] [:wall :open :open :open :open :open :open :wall] [:wall :open :wall :open :open :open :open :wall] [:wall :open :open :open :open :wall :target :wall] [:wall :wall :open :wall :target :open :open :wall] [:open :wall :open :open :open :open :target :wall] [:open :wall :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}
{:level [[:wall :wall :wall :wall :wall :wall :open :open] [:wall :open :open :target :open :wall :open :open] [:wall :open :open :open :open :wall :wall :wall] [:wall :open :wall :open :open :target :open :wall] [:wall :target :open :open :wall :wall :open :wall] [:wall :open :open :open :wall :wall :open :wall] [:wall :wall :wall :open :open :open :open :wall] [:open :open :wall :wall :wall :wall :wall :wall]], :positions {:player [0 0], :blocks #{[0 1]}}}

])
